"""empty message

Revision ID: 27e3fdf49767
Revises: b880289a673
Create Date: 2015-12-01 11:54:04.567000

"""

# revision identifiers, used by Alembic.
revision = '27e3fdf49767'
down_revision = 'b880289a673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('general', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'general')
    ### end Alembic commands ###
