"""empty message

Revision ID: b880289a673
Revises: None
Create Date: 2015-11-28 19:50:45.056000

"""

# revision identifiers, used by Alembic.
revision = 'b880289a673'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'html')
    ### end Alembic commands ###
